### ISSUE TITLE
The code makes the dropdown display Popular, but does not change sorting

### ISSUE THREAD

**Issue by djfrez** [Ferguson230/Filter-by-Popularity-Instead-of-Relevance-In-Woocommerce-Product-Search-page#1]
I have tried the code which removes the 'Relevance' sort option and has 'Popularity' as the default, but the order of the search results still does not sort to popularity unless I actually click it from the drop down options.

This obviously defies the point, as we want the customer to search the products and for them to sort automatically into order of popularity. Would you be able to offer any solutions?

Thanks for any help in advance, really struggling to find any solutions to this issue.

(just replicated renekcouture's comment as it explains perfectly what we are experiencing as well)

**Comment by Ferguson230** [comment]
The code has been refined and transformed into a WordPress/Woocommerce plugin for enhanced functionality. For the latest instructions and details, please refer to the readme file accompanying the plugin.
